#!/usr/bin/env bash
# e2e_test/gen-oc-toml.sh — write the oc.toml that setup.sh demands, for a
# checkout that has none (a CI runner).
#
# WHY THIS EXISTS
# oc.toml is gitignored, and setup.sh refuses to run without one that (a) binds
# the non-prod port and (b) carries an explicit repo-local sqlite DSN. Those two
# refusals are the prod guards — they are the reason this suite cannot stomp a
# real station. So a runner cannot skip them; it has to satisfy them. Until this
# script existed the only instructions were prose in setup.sh's FATAL message,
# which meant every automated caller had to reinvent the file — and a caller that
# reinvented it slightly wrong (`cp oc.toml.example oc.toml`, say) got a refusal
# it could not explain. This is the one named way to produce it.
#
# FAIL-CLOSED ON AN EXISTING FILE, ON PURPOSE
# If oc.toml already exists we refuse rather than overwrite. On a developer's Mac
# that file is their real local configuration — possibly pointing at the
# canonical ~/.officraft DB. Overwriting it would be a silent, unrecoverable edit
# to something this script does not own. Callers that genuinely want a fresh one
# delete theirs first, deliberately.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
TARGET="$REPO_ROOT/oc.toml"

# The port and DSN below are the two values setup.sh checks. They are written
# here rather than sourced from setup.sh because setup.sh reads them FROM this
# file's output — one of the two has to state them, and a generator stating its
# own output is the honest direction.
PORT=8791
DSN="sqlite:///var/data/e2e.db"

if [ -e "$TARGET" ]; then
  echo "[gen-oc-toml] REFUSED: $TARGET already exists." >&2
  echo "[gen-oc-toml] This script never overwrites it — on a dev machine that file is" >&2
  echo "[gen-oc-toml] real configuration and may point at the production DB. Remove it" >&2
  echo "[gen-oc-toml] yourself if you really want a fresh e2e one." >&2
  exit 2
fi

cat > "$TARGET" <<EOF
# Generated by e2e_test/gen-oc-toml.sh — the isolated e2e station's config.
# NOT production: port $PORT and a repo-local DSN are what setup.sh's prod
# guards insist on. gitignored.
[server]
port = $PORT

[storage]
dsn = "$DSN"
EOF

echo "[gen-oc-toml] wrote $TARGET (port=$PORT dsn=$DSN)"
