-- +goose Up
-- T-2 step A — 先砍資料. Every `lessons` overlay whose task_type is not
-- 'general' is deleted here, and the column itself is left alone: dropping it
-- is a SEPARATE, LATER change, and the order is the whole point.
--
-- 🔴 WHY DATA FIRST, NOT THE COLUMN FIRST. `lessons` is keyed
-- (role_key, task_type) — see 00001_schema.sql, which states the shard reason.
-- Remove the column while several task_types still exist for one role_key and
-- those rows collapse onto ONE surviving key: a lossy fold, and which row wins
-- is not something the caller gets to choose. Deleting first means the later
-- drop meets a table where role_key is already unique on its own, so the fold
-- is an identity. Owner ruling, 2026-08-26: 「應該先砍資料再砍欄位」「避免
-- duplicate」.
--
-- 🔴 CORRECTION, 2026-08-27 — AN EARLIER VERSION OF THIS COMMENT WAS WRONG
-- ABOUT THE MECHANISM, and the correction is recorded rather than quietly
-- swapped because the wrong version travelled into a ticket. It said SQLite's
-- `ALTER TABLE ... DROP COLUMN` "does not report that as a conflict; it is a
-- lossy fold". MEASURED, sqlite3 3.51.0:
--   sqlite> ALTER TABLE lessons DROP COLUMN task_type;
--   Error: in prepare, cannot drop PRIMARY KEY column: "task_type"
-- (positive control: dropping a NON-key column on the same table answers ok.)
-- SQLite REFUSES outright. It never gets as far as folding anything.
--
-- THE ORDERING ABOVE IS STILL CORRECT; ONLY THE REASON MOVED. Because ALTER
-- cannot do it at all, the column drop has to be a create/copy/drop/rename
-- REBUILD — and the lossy fold lives in that rebuild's copy step, not in
-- ALTER. 00062 does exactly that rebuild and disarms the fold by copying with
-- a plain `INSERT` (not `OR REPLACE` / `OR IGNORE`), so a station where this
-- DELETE never ran stops with a UNIQUE constraint instead of silently keeping
-- whichever row happened to be last. Both directions are measured in
-- TestMigration00062RefusesToFoldDuplicateRoleKeys and
-- TestMigration00062SqliteRefusesToDropAPrimaryKeyColumn.
--
-- EDITING AN APPLIED MIGRATION'S COMMENT IS SAFE HERE, AND THAT WAS CHECKED
-- RATHER THAN ASSUMED: goose v3.27.2 records only (version_id, is_applied,
-- tstamp) — `PRAGMA table_info(goose_db_version)` on a live station returns
-- exactly [id version_id is_applied tstamp], with nowhere to hold a digest —
-- and the module carries no checksum/sha256/md5 code on any migration path
-- (its one crc32 is an advisory-lock id). Measured end to end: migrate a temp
-- DB to head, add a comment line to THIS file, migrate again — goose accepts
-- it and re-runs nothing. The SQL below is byte-identical to what ran.
--
-- 🔴 THE PREDICATE IS "NOT general", NOT A LIST. A migration written against
-- an enumerated snapshot of today's rows would silently spare anything written
-- between the snapshot and the moment it runs — and this table is written by
-- live agents, so that window is real on every station this ships to. The
-- surviving set is defined by the value that stays, which cannot go stale.
--
-- 🔴 IDEMPOTENT BY SHAPE. A DELETE whose predicate is already unsatisfied
-- affects nothing and does not error, so a re-run (goose down/up, a replayed
-- upgrade) is a no-op rather than a second, different outcome.
--
-- 🔴 `general` ROWS ARE NOT TOUCHED — that is the one irreversible risk in this
-- change, because a wrongly deleted lessons doc is not recoverable from
-- anywhere this migration knows about. `<>` (not `LIKE`, not a prefix match) is
-- what keeps the comparison byte-exact: no wildcard, no collation surprise, no
-- neighbouring key ('general-something') mistaken for the one being spared.
--
-- 🔴 THE PREDICATE DOES NOT DEFEND AGAINST NULL, AND DOES NOT NEED TO.
-- `NULL <> 'general'` evaluates to NULL, not TRUE, so a NULL task_type would
-- be SPARED by this DELETE rather than removed. That hole is closed one level
-- down and not here: lessons.task_type is declared `TEXT NOT NULL` in
-- 00001_schema.sql, so a NULL can never be stored to begin with — writing one
-- is refused by SQLite with "NOT NULL constraint failed: lessons.task_type"
-- (extended result code 1299 / SQLITE_CONSTRAINT_NOTNULL). Measured, not
-- assumed. Stated here so the next reader does not have to re-derive it, and
-- so that anyone who ever proposes relaxing that NOT NULL knows this migration
-- is one of the things leaning on it.
DELETE FROM lessons
 WHERE task_type <> 'general';

-- 🔴 THE SECOND DOOR — document_history. Deleting the lessons rows above only
-- makes the table general-only AT THIS INSTANT. document_history is a separate
-- table holding retained revisions, and the restore route writes straight back
-- into `lessons` from it: for document_kind = 'lessons' the restore arm of
-- restoreDocumentHistory splits document_key on "::" and hands the task_type it
-- finds to putLessonsOn VERBATIM — no step on that path compares the value to
-- 'general'. Leaving those rows would therefore leave a live writer able to put
-- a non-general row back, and the entire reason this migration runs before the
-- column drop is that no such row may exist when the fold happens. Measured
-- end-to-end, not inferred: see
-- TestMigration00061RestoreCannotPutANonGeneralLessonBack, which without this
-- statement observes the restore answer 200 and the deleted row reappear.
--
-- 🔑 The precedent is in the same codebase. DeleteLessonsForRole (dal.go)
-- deletes the lessons rows and their "<role_key>::" history rows in ONE
-- transaction, because a document and its retained versions are one thing.
-- This statement is the migration-shaped twin of that cascade.
--
-- 🔴 THE PREDICATE MIRRORS THE PARSE, NOT THE CONSTRUCTION — and that
-- distinction is the whole correctness argument. The key is BUILT as
-- roleKey || '::' || taskType, but it was READ back by historyKeyParts in
-- api_document_history.go with a SplitN(key, "::", 2). That parse is described
-- in the past tense because T-2 removed it — see the 2026-08-27 note at the
-- end of this comment block, which is where what replaced it is written down.
-- Under that parse the task_type the restore would actually write is
-- everything after the FIRST "::", however many separators the key contains. So this predicate splits at the first "::" too
-- (instr + substr, never LIKE — no wildcard, no collation, no escaping
-- question). A role_key that itself contains "::" is thereby handled the way
-- the restore handles it rather than the way it was written: key
-- 'a::b::general' restores task_type 'b::general', which is not 'general', and
-- this predicate deletes it. Agreeing with the parse is what makes "no restore
-- can reseed a non-general row" true rather than approximately true.
--
-- 🔴 WHAT IS DELIBERATELY SPARED, so it is not read as an oversight. The three
-- conditions below were exactly historyKeyParts' notion of a VALID lessons key
-- AT THE TIME THIS RAN (both sides of the first "::" non-empty), plus "and the
-- task_type is not general". Rows whose key has no "::" at all, or an empty
-- role_key side ('::general'), or an empty task_type side ('assistant::') are
-- NOT deleted: documentHistoryAllowed refuses such a key with 400 before any
-- restore runs, so none of them can reseed anything, and this is an
-- irreversible DELETE that gets to remove only what it can show is dangerous.
-- Live writers cannot produce those shapes either — both writers (in
-- api_roles.go) build the key from two non-empty path segments. If a later
-- change ever makes such a key restorable, that change owns cleaning them up.
--
-- 🔴 THAT LAST SENTENCE WAS NEARLY CASHED IN, 2026-08-27 — recorded because
-- a load-bearing invariant is worth more than a tidy file. T-2 (00062) removed
-- the task_type axis and, with it, the two-halves parse this paragraph leans
-- on; a first cut reduced historyKeyParts to "the key is non-empty", which
-- retired the 400 WITHOUT retiring these rows. `assistant::` briefly became a
-- key you could list and RESTORE, and the restore materialised a `lessons` row
-- under it — exactly the reseed this paragraph promises cannot happen. The
-- refusal was put back before that shipped: since T-2 a lessons key carrying
-- "::" names nothing, so historyKeyParts refuses it OUTRIGHT rather than by
-- failing to split it. The 400 is therefore still true, and still stated
-- forward rather than as a leftover — see historyKeyParts and
-- api_document_history_lessons_key_t2_test.go. Anyone loosening that door
-- again inherits the cleanup this paragraph deferred.
--
-- 🔴 EVERY OTHER document_kind IS UNTOUCHED — insight, global_context,
-- role_definition, task_description, task_title, the boot-document kinds and
-- both task-manual series. `document_kind = 'lessons'` is an exact equality on
-- a column, the same fail-closed shape 00045 used, and it is asserted rather
-- than asserted-by-comment (see the untouched-kinds fixture in the test file).
DELETE FROM document_history
 WHERE document_kind = 'lessons'
   AND instr(document_key, '::') > 1
   AND substr(document_key, instr(document_key, '::') + 2) <> ''
   AND substr(document_key, instr(document_key, '::') + 2) <> 'general';

-- +goose Down
-- NOT REVERSIBLE, on BOTH tables. The Up deleted lessons rows AND their
-- retained document_history revisions, and this migration kept no copy of
-- either anywhere — rolling back does not and cannot bring them back. Writing a Down
-- that reinstated empty or synthesized rows would be a lie about what is
-- recoverable, so the rollback is an explicit no-op: it retreats the CODE, not
-- the data. (The original text of what was deleted was captured out-of-band
-- before this landed; the task's artifact record, not this file, is where that
-- lives.)
SELECT 1;
