import json, pathlib

C = [
 ("plain_ascii", "Midnight"),
 ("builtin_zh", "辦公室"),
 ("builtin_en", "Office"),
 ("builtin_upper", "OFFICE"),
 ("builtin_pad_ascii", "  OFFICE  "),
 ("builtin_dotted_I", "OFFİCE"),
 ("builtin_fullwidth", "ＯＦＦＩＣＥ"),
 ("builtin_kelvin", "OFFICEK"),
 ("bom_prefix_zh", "﻿辦公室"),
 ("bom_suffix_zh", "辦公室﻿"),
 ("bom_prefix_en", "﻿Office"),
 ("zwsp_inside", "辦​公室"),
 ("zwnj_persian", "می‌خواهم"),
 ("zwj_family_emoji", "家庭 \U0001f468‍\U0001f469‍\U0001f467"),
 ("zwj_rainbow_flag", "Pride \U0001f3f3️‍\U0001f308"),
 ("zwj_woman_tech", "Coder \U0001f469‍\U0001f4bb"),
 ("emoji_simple", "\U0001f319 Midnight \U0001f319"),
 ("emoji_vs16_only", "Heart ❤️"),
 ("devanagari_zwj", "क्‍ष theme"),
 ("arabic_plain", "سمة داكنة"),
 ("hebrew_plain", "ערכת נושא כהה"),
 ("arabic_with_alm", "سمة؜داكنة"),
 ("rtl_override", "‮abc"),
 ("cjk", "深海の夜"),
 ("korean", "밤하늘"),
 ("ideographic_space_only", "　"),
 ("ideographic_space_pad", "　辦公室　"),
 ("ideographic_space_office", "　Office　"),
 ("nbsp_only", " "),
 ("nbsp_pad_office", " Office "),
 ("nel_u0085", "Office"),
 ("line_sep_u2028", "Mid night"),
 ("para_sep_u2029", "Mid night"),
 ("ogham_space", " Office "),
 ("mongolian_vowel_sep", "Off᠎ice"),
 ("soft_hyphen", "Off­ice"),
 ("tab_pad", "\tMidnight\t"),
 ("newline_inside", "Mid\nnight"),
 ("empty", ""),
 ("space_only", "   "),
 ("len_80_bmp", "a" * 80),
 ("len_81_bmp", "a" * 81),
 ("len_80_astral", "\U0001f319" * 80),
 ("len_81_astral", "\U0001f319" * 81),
 ("spoof_builtin_marker_zh", "辦公室（內建）"),
 ("spoof_builtin_marker_en", "Office (Built-in)"),
 ("new_theme_zh", "新主題"),
 ("new_theme_en", "New theme"),
 ("nfd_office", "Offíce"),
 ("variation_sel_office", "Office️"),
 ("del_u007f", "Office"),
 ("c1_u009b", "Office"),
 ("tag_char", "Office\U000e0041"),
 ("word_joiner", "Off⁠ice"),
 ("lre_u202a", "‪Office"),
 ("isolate_u2066", "⁦Office"),
 ("rlm_u200f", "‏سمة"),
]

p = pathlib.Path(__file__).with_name("name-cases.json")
p.write_text(json.dumps([{"k": k, "n": n} for k, n in C], ensure_ascii=False, indent=0), encoding="utf-8")
print("wrote", p, len(C), "cases")
